export default{
  login: "saeedberzawi",
  id: 101089452,
  node_id: "U_kgDOBgaArA",
  avatar_url: "https://avatars.githubusercontent.com/u/101089452?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/saeedberzawi",
  html_url: "https://github.com/saeedberzawi",
  followers_url: "https://api.github.com/users/saeedberzawi/followers",
  following_url: "https://api.github.com/users/saeedberzawi/following{/other_user}",
  gists_url: "https://api.github.com/users/saeedberzawi/gists{/gist_id}",
  starred_url: "https://api.github.com/users/saeedberzawi/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/saeedberzawi/subscriptions",
  organizations_url: "https://api.github.com/users/saeedberzawi/orgs",
  repos_url: "https://api.github.com/users/saeedberzawi/repos",
  events_url: "https://api.github.com/users/saeedberzawi/events{/privacy}",
  received_events_url: "https://api.github.com/users/saeedberzawi/received_events",
  type: "User",
  site_admin: false,
  name: "Saeed Al Berzawi",
  company: null,
  blog: "https://al-berzawi.netlify.app/",
  location: null,
  email: null,
  hireable: null,
  bio: " Front-end Web Developer Experience in React Framework and sass, git & GitHub, API, nodejs.",
  twitter_username: "SMhdBRZ",
  public_repos: 19,
  public_gists: 0,
  followers: 2,
  following: 25,
  created_at: "2022-03-07T07:09:54Z",
  updated_at: "2022-09-17T10:54:49Z"
  }
